### ISSUE TITLE
RuntimeError: Could not open '../all_models/mobilenet_v2_1.0_224_quant_edgetpu.tflite'.`

### ISSUE THREAD

**Issue by arvindr9** [google-coral/examples-camera#10]
When I type python classify.py after installing gstreamer and sh install_requirements.sh, I get the following error on my raspberry pi.

`Loading ../all_models/mobilenet_v2_1.0_224_quant_edgetpu.tflite with ../all_models/imagenet_labels.txt labels.
Traceback (most recent call last):
  File "classify.py", line 74, in <module>
    main()
  File "classify.py", line 52, in main
    engine = ClassificationEngine(args.model)
  File "/usr/local/lib/python3.5/dist-packages/edgetpu/classification/engine.py", line 38, in __init__
    super().__init__(model_path)
  File "/usr/local/lib/python3.5/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 300, in __init__
    this = _edgetpu_cpp_wrapper.new_BasicEngine(*args)
RuntimeError: Could not open '../all_models/mobilenet_v2_1.0_224_quant_edgetpu.tflite'.`

It looks as if there is a model that is unable to be opened. Is there something missing from the install_requirements.sh file?

**Comment by novusli** [comment]
I have the same issue, any solutions?
