### ISSUE TITLE
Error in AllocateTensors

### ISSUE THREAD

**Issue by aaroninaustin** [google-coral/examples-camera#34]
Attempting to run gstreamer detect.py example with a USB camera on Coral Dev board.

tflite-runtime
Version: 1.14.0
I'm seeing this error output:

```
Loading ../all_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite with ../all_models/coco_labels.txt labels.
INFO: Initialized TensorFlow Lite runtime.
Traceback (most recent call last):
  File "detect.py", line 157, in <module>
    main()
  File "detect.py", line 127, in main
    interpreter.allocate_tensors()
  File "/home/mendel/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/mendel/.local/lib/python3.7/site-packages/tflite_runtime/interpreter_wrapper.py", line 111, in AllocateTensors
    return _interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Internal: :77 tf_lite_type != kTfLiteUInt8 (2 != 3)Node number 2 (EdgeTpuDelegateForCustomOp) failed to prepare.
```
Looking for some guidance on this issue. 
The other Coral edgetpu examples still work without issue -

**Comment by mtyka** [comment]
With the latest Mendel image you need to install
```pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0-cp37-cp37m-linux_aarch64.whl```
(see https://coral.ai/docs/dev-board/get-started/
and this issue:
https://github.com/google-coral/edgetpu/issues/44)
